name: Simple Docker Publish

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: hello-world-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Kodu checkout et
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2️⃣ Script'e chmod ver ve çalıştır
      - name: Run script
        id: run_script
        run: |
          chmod +x hello.sh
          ./hello.sh
          echo "message=Script executed successfully" >> $GITHUB_OUTPUT

      # 3️⃣ Output değerini kullan
      - name: Show message output
        run: | 
            echo "Output from previous step: ${{ steps.run_script.outputs.message }}"

      # 4️⃣ Script'i artifact olarak yükle
      - name: Upload script as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-script
          path: hello.sh

      # 5️⃣ Docker Hub'a login ol
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6️⃣ Docker image build et
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      # 7️⃣ Docker image push et
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
